In [10]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [11]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Ushuaia,AR,2021-01-20 17:38:02,-54.8000,-68.3000,59.00,47,40,16.11
1,1,Corrales,US,2021-01-20 17:39:12,35.2378,-106.6067,34.00,82,97,3.98
2,2,Zaragoza,ES,2021-01-20 17:36:35,41.6561,-0.8773,46.00,93,75,9.22
3,3,Rikitea,PF,2021-01-20 17:39:12,-23.1203,-134.9692,78.10,75,25,15.17
4,4,Airai,TL,2021-01-20 17:39:12,-8.9266,125.4092,61.59,100,83,2.62

In [12]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [13]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [14]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of Wind Speek
locations = city_data_df[["Lat", "Lng"]]
winds = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=winds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [20]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Rikitea,PF,2021-01-20 17:39:12,-23.1203,-134.9692,78.10,75,25,15.17
5,5,Dingle,PH,2021-01-20 17:39:12,10.9995,122.6711,75.24,92,98,4.00
8,8,Puerto Ayora,EC,2021-01-20 17:39:12,-0.7393,-90.3518,82.40,69,20,23.02
13,13,Kloulklubed,PW,2021-01-20 17:39:13,7.0419,134.2556,80.60,83,75,5.75
17,17,Butaritari,KI,2021-01-20 17:39:13,3.0707,172.7902,79.92,81,45,18.37
30,30,Ahuimanu,US,2021-01-20 17:39:15,21.4447,-157.8378,75.20,73,40,10.36
34,34,Belmonte,BR,2021-01-20 17:39:15,-15.8631,-38.8828,84.20,58,40,10.36
35,35,Bathsheba,BB,2021-01-20 17:39:16,13.2167,-59.5167,82.40,65,40,18.41
37,37,Black River,JM,2021-01-20 17:39:16,18.0264,-77.8487,84.00,74,40,19.57
41,41,Sao Joao Da Barra,BR,2021-01-20 17:39:16,-21.6403,-41.0511,87.80,42,0,18.41

In [21]:
preferred_cities_df.count()

City_ID       171
City          171
Country       170
Date          171
Lat           171
Lng           171
Max Temp      171
Humidity      171
Cloudiness    171
Wind Speed    171
dtype: int64

In [24]:
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df.count()

City_ID       170
City          170
Country       170
Date          170
Lat           170
Lng           170
Max Temp      170
Humidity      170
Cloudiness    170
Wind Speed    170
dtype: int64

In [25]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                 City Country  Max Temp      Lat       Lng Hotel Name
3             Rikitea      PF     78.10 -23.1203 -134.9692
5              Dingle      PH     75.24  10.9995  122.6711
8        Puerto Ayora      EC     82.40  -0.7393  -90.3518
13        Kloulklubed      PW     80.60   7.0419  134.2556
17         Butaritari      KI     79.92   3.0707  172.7902
30           Ahuimanu      US     75.20  21.4447 -157.8378
34           Belmonte      BR     84.20 -15.8631  -38.8828
35          Bathsheba      BB     82.40  13.2167  -59.5167
37        Black River      JM     84.00  18.0264  -77.8487
41  Sao Joao Da Barra      BR     87.80 -21.6403  -41.0511

In [33]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [42]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")  
        
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Rikitea,PF,78.10,-23.1203,-134.9692,Pension Maro'i
5,Dingle,PH,75.24,10.9995,122.6711,SEGAYA PROPERTY
8,Puerto Ayora,EC,82.40,-0.7393,-90.3518,Castillo Galapagos
13,Kloulklubed,PW,80.60,7.0419,134.2556,Storyboard Beach Resort
17,Butaritari,KI,79.92,3.0707,172.7902,Isles Sunset Lodge
30,Ahuimanu,US,75.20,21.4447,-157.8378,Paradise Bay Resort
34,Belmonte,BR,84.20,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
35,Bathsheba,BB,82.40,13.2167,-59.5167,Atlantis Hotel
37,Black River,JM,84.00,18.0264,-77.8487,Idlers' Rest Beach Hotel
41,Sao Joao Da Barra,BR,87.80,-21.6403,-41.0511,Pousada Porto De Canoas

In [43]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [44]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [45]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [46]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))